import { afterEach, describe, expect, it, vi } from "vitest";
import { BookingCreateOutcomeUnknownError, BookingCreateRecoveryUnavailableError, clearPendingBookingCreate, dispatchPendingBookingCreate, parsePendingBookingCreate, pendingBookingCreateHref, readPendingBookingCreate, type PendingBookingCreate } from "../pendingBookingCreate";
const b:PendingBookingCreate={kind:'individual',salonId:'11111111-1111-4111-8111-111111111111',idempotencyKey:'21111111-1111-4111-8111-111111111111',pricingFingerprint:'a'.repeat(64)};
function storage():Storage{const m=new Map<string,string>();return{get length(){return m.size;},key:n=>[...m.keys()][n]??null,getItem:k=>m.get(k)??null,setItem:(k,v)=>{m.set(k,v);},removeItem:k=>{m.delete(k);},clear:()=>m.clear()};}
afterEach(()=>vi.useRealTimers());
describe.each(['individual','sequence'] as const)('%s pre-dispatch authority',kind=>{
 const binding={...b,kind};
 it('strictly round trips internal href',()=>{expect(parsePendingBookingCreate(pendingBookingCreateHref(binding)!.split('/booking/recover-booking')[1])).toEqual(binding);expect(parsePendingBookingCreate('#booking=individual.invalid')).toBeNull();});
 it('persists before dispatch and retains network failure across reload',async()=>{const s=storage(),invoke=vi.fn(async()=>{expect(readPendingBookingCreate(s,b.salonId)).toBeTruthy();throw Error('synthetic network');});await expect(dispatchPendingBookingCreate({binding,storage:s,invoke,classify:()=> 'succeeded'})).rejects.toBeInstanceOf(BookingCreateOutcomeUnknownError);expect(s.getItem(s.key(0)!)).toBe(pendingBookingCreateHref(binding));});
 it.each(['succeeded','rejected'] as const)('clears exact authority only after %s proof',async outcome=>{const s=storage();expect(await dispatchPendingBookingCreate({binding,storage:s,invoke:async()=>42,classify:()=>outcome})).toBe(42);expect(s.length).toBe(0);});
 it('keeps unknown and blocks a different intent or flow without replay',async()=>{const s=storage(),invoke=vi.fn(async()=>null);await expect(dispatchPendingBookingCreate({binding,storage:s,invoke,classify:()=> 'unknown'})).rejects.toMatchObject({recoveryHref:pendingBookingCreateHref(binding)});await expect(dispatchPendingBookingCreate({binding:{...binding,kind:kind==='individual'?'sequence':'individual',idempotencyKey:'31111111-1111-4111-8111-111111111111'},storage:s,invoke,classify:()=> 'unknown'})).rejects.toMatchObject({recoveryHref:pendingBookingCreateHref(binding)});expect(invoke).toHaveBeenCalledTimes(1);});
 it.each(['write','readback'])('blocks before dispatch on %s failure',async stage=>{const s=storage(),invoke=vi.fn();s.setItem=stage==='write'?()=>{throw Error('denied');}:()=>{};await expect(dispatchPendingBookingCreate({binding,storage:s,invoke,classify:()=> 'succeeded'})).rejects.toBeInstanceOf(BookingCreateRecoveryUnavailableError);expect(invoke).not.toHaveBeenCalled();});
 it('does not clear or read another tenant/intent',async()=>{const s=storage();await dispatchPendingBookingCreate({binding,storage:s,invoke:async()=>0,classify:()=> 'unknown'}).catch(()=>{});clearPendingBookingCreate(s,{...binding,pricingFingerprint:'b'.repeat(64)});expect(s.length).toBe(1);expect(readPendingBookingCreate(s,'31111111-1111-4111-8111-111111111111')).toBeNull();});
 it('times out even when transport ignores abort, without a second dispatch',async()=>{vi.useFakeTimers();const s=storage(),invoke=vi.fn(()=>new Promise<null>(()=>{}));const caught=dispatchPendingBookingCreate({binding,storage:s,invoke,classify:()=> 'succeeded'}).catch(e=>e);await vi.advanceTimersByTimeAsync(12000);expect(await caught).toBeInstanceOf(BookingCreateOutcomeUnknownError);expect(invoke).toHaveBeenCalledTimes(1);expect(s.length).toBe(1);});
 it('concurrent calls dispatch at most once',async()=>{const s=storage(),invoke=vi.fn(async()=>null);const result=await Promise.allSettled([dispatchPendingBookingCreate({binding,storage:s,invoke,classify:()=> 'unknown'}),dispatchPendingBookingCreate({binding,storage:s,invoke,classify:()=> 'unknown'})]);expect(result.every(x=>x.status==='rejected')).toBe(true);expect(invoke).toHaveBeenCalledTimes(1);});
});
