-- Folded-history marker for production migration 20260506004817.
-- Original production name: create_public_booking_accept_client_email.
-- Its schema effect is represented by the later folded baseline.
