-- Folded-history marker for production migration 20260429130000.
-- Original production name: bookings_rpc_and_authenticated_insert.
-- Its schema effect is represented by the later folded baseline.
