-- Folded-history marker for production migration 20260430170000.
-- Original production name: bookings_unique_slot_and_price_snapshot.
-- Its schema effect is represented by the later folded baseline.
