-- Cross-purpose Resend delivery evidence for the unified NailIQ email registry.
--
-- This ledger is additive. Booking, owner-alert and OTP mail keep their stronger
-- domain-specific claims and reconciliation tables. The shared ledger provides
-- a PII-free answer for every registered email purpose without treating provider
-- acceptance as final delivery.

CREATE TABLE public.registered_email_delivery_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_event_id text NOT NULL UNIQUE,
  provider_message_id text NOT NULL,
  email_key text NOT NULL,
  audience text NOT NULL,
  event_type text NOT NULL,
  delivery_status text NOT NULL,
  recipient_fingerprint text NOT NULL,
  recipient_count integer NOT NULL,
  occurred_at timestamptz NOT NULL,
  payload_fingerprint text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT registered_email_delivery_provider_event_check CHECK (
    provider_event_id ~ '^[!-~]{1,255}$'
  ),
  CONSTRAINT registered_email_delivery_provider_message_check CHECK (
    provider_message_id ~ '^[!-~]{1,255}$'
  ),
  CONSTRAINT registered_email_delivery_key_check CHECK (
    email_key ~ '^[a-z0-9_]{1,64}$'
  ),
  CONSTRAINT registered_email_delivery_audience_check CHECK (
    audience IN ('customer', 'owner', 'operator', 'security')
  ),
  CONSTRAINT registered_email_delivery_event_check CHECK (
    event_type IN (
      'email.sent', 'email.delivered', 'email.delivery_delayed',
      'email.failed', 'email.suppressed', 'email.bounced', 'email.complained'
    )
  ),
  CONSTRAINT registered_email_delivery_status_check CHECK (
    (event_type = 'email.sent' AND delivery_status = 'provider_accepted') OR
    (event_type = 'email.delivered' AND delivery_status = 'delivered') OR
    (event_type = 'email.delivery_delayed' AND delivery_status = 'delivery_delayed') OR
    (event_type = 'email.failed' AND delivery_status = 'failed') OR
    (event_type = 'email.suppressed' AND delivery_status = 'suppressed') OR
    (event_type = 'email.bounced' AND delivery_status = 'bounced') OR
    (event_type = 'email.complained' AND delivery_status = 'complained')
  ),
  CONSTRAINT registered_email_delivery_recipient_fingerprint_check CHECK (
    recipient_fingerprint ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT registered_email_delivery_recipient_count_check CHECK (
    recipient_count BETWEEN 1 AND 100
  ),
  CONSTRAINT registered_email_delivery_payload_fingerprint_check CHECK (
    payload_fingerprint ~ '^[0-9a-f]{64}$'
  )
);

CREATE INDEX registered_email_delivery_message_timeline_idx
  ON public.registered_email_delivery_events (
    provider_message_id, recipient_fingerprint, occurred_at DESC, id DESC
  );

CREATE INDEX registered_email_delivery_operations_idx
  ON public.registered_email_delivery_events (
    email_key, audience, delivery_status, occurred_at DESC, id DESC
  );

ALTER TABLE public.registered_email_delivery_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registered_email_delivery_events FORCE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.registered_email_delivery_events
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON SEQUENCE public.registered_email_delivery_events_id_seq
  FROM PUBLIC, anon, authenticated, service_role;

CREATE POLICY registered_email_delivery_events_deny_direct
  ON public.registered_email_delivery_events AS RESTRICTIVE
  FOR ALL TO PUBLIC
  USING (false)
  WITH CHECK (false);

CREATE OR REPLACE FUNCTION public.record_resend_registered_email_delivery_event(
  p_provider_event_id text,
  p_provider_message_id text,
  p_email_key text,
  p_audience text,
  p_event_type text,
  p_recipient_fingerprint text,
  p_recipient_count integer,
  p_occurred_at timestamptz,
  p_payload_fingerprint text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_delivery_status text;
  v_inserted_id bigint;
  v_existing public.registered_email_delivery_events%ROWTYPE;
BEGIN
  IF p_provider_event_id IS NULL
     OR p_provider_event_id !~ '^[!-~]{1,255}$'
     OR p_provider_message_id IS NULL
     OR p_provider_message_id !~ '^[!-~]{1,255}$'
     OR p_email_key IS NULL
     OR p_email_key !~ '^[a-z0-9_]{1,64}$'
     OR p_audience IS NULL
     OR p_audience NOT IN ('customer', 'owner', 'operator', 'security')
     OR p_event_type IS NULL
     OR p_event_type NOT IN (
       'email.sent', 'email.delivered', 'email.delivery_delayed',
       'email.failed', 'email.suppressed', 'email.bounced', 'email.complained'
     )
     OR p_recipient_fingerprint IS NULL
     OR p_recipient_fingerprint !~ '^[0-9a-f]{64}$'
     OR p_recipient_count IS NULL
     OR p_recipient_count NOT BETWEEN 1 AND 100
     OR p_occurred_at IS NULL
     OR p_occurred_at > now() + interval '10 minutes'
     OR p_payload_fingerprint IS NULL
     OR p_payload_fingerprint !~ '^[0-9a-f]{64}$'
  THEN
    RETURN jsonb_build_object('success', false, 'code', 'event_rejected');
  END IF;

  v_delivery_status := CASE p_event_type
    WHEN 'email.sent' THEN 'provider_accepted'
    WHEN 'email.delivered' THEN 'delivered'
    WHEN 'email.delivery_delayed' THEN 'delivery_delayed'
    WHEN 'email.failed' THEN 'failed'
    WHEN 'email.suppressed' THEN 'suppressed'
    WHEN 'email.bounced' THEN 'bounced'
    WHEN 'email.complained' THEN 'complained'
  END;

  INSERT INTO public.registered_email_delivery_events (
    provider_event_id,
    provider_message_id,
    email_key,
    audience,
    event_type,
    delivery_status,
    recipient_fingerprint,
    recipient_count,
    occurred_at,
    payload_fingerprint
  ) VALUES (
    p_provider_event_id,
    p_provider_message_id,
    p_email_key,
    p_audience,
    p_event_type,
    v_delivery_status,
    p_recipient_fingerprint,
    p_recipient_count,
    p_occurred_at,
    p_payload_fingerprint
  )
  ON CONFLICT (provider_event_id) DO NOTHING
  RETURNING id INTO v_inserted_id;

  IF v_inserted_id IS NOT NULL THEN
    RETURN jsonb_build_object(
      'success', true,
      'code', 'event_applied',
      'delivery_status', v_delivery_status
    );
  END IF;

  SELECT e.*
  INTO v_existing
  FROM public.registered_email_delivery_events AS e
  WHERE e.provider_event_id = p_provider_event_id;

  IF v_existing.provider_message_id = p_provider_message_id
     AND v_existing.email_key = p_email_key
     AND v_existing.audience = p_audience
     AND v_existing.event_type = p_event_type
     AND v_existing.recipient_fingerprint = p_recipient_fingerprint
     AND v_existing.recipient_count = p_recipient_count
     AND v_existing.occurred_at = p_occurred_at
     AND v_existing.payload_fingerprint = p_payload_fingerprint
  THEN
    RETURN jsonb_build_object(
      'success', true,
      'code', 'event_replay',
      'delivery_status', v_existing.delivery_status
    );
  END IF;

  RETURN jsonb_build_object('success', false, 'code', 'event_conflict');
END;
$$;

CREATE OR REPLACE FUNCTION public.load_registered_email_delivery_truth(
  p_email_key text DEFAULT NULL,
  p_audience text DEFAULT NULL,
  p_delivery_status text DEFAULT NULL,
  p_limit integer DEFAULT 100
)
RETURNS TABLE (
  provider_message_id text,
  email_key text,
  audience text,
  delivery_status text,
  event_type text,
  recipient_count integer,
  occurred_at timestamptz,
  received_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    e.provider_message_id,
    e.email_key,
    e.audience,
    e.delivery_status,
    e.event_type,
    e.recipient_count,
    e.occurred_at,
    e.received_at
  FROM public.registered_email_delivery_events AS e
  WHERE (p_email_key IS NULL OR e.email_key = p_email_key)
    AND (p_audience IS NULL OR e.audience = p_audience)
    AND (p_delivery_status IS NULL OR e.delivery_status = p_delivery_status)
  ORDER BY e.occurred_at DESC, e.id DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 100), 1), 500)
$$;

REVOKE ALL ON FUNCTION public.record_resend_registered_email_delivery_event(
  text, text, text, text, text, text, integer, timestamptz, text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.load_registered_email_delivery_truth(
  text, text, text, integer
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.record_resend_registered_email_delivery_event(
  text, text, text, text, text, text, integer, timestamptz, text
) TO service_role;
GRANT EXECUTE ON FUNCTION public.load_registered_email_delivery_truth(
  text, text, text, integer
) TO service_role;

COMMENT ON TABLE public.registered_email_delivery_events IS
  'PII-free signed Resend delivery events for registered NailIQ email purposes; domain-specific ledgers remain authoritative.';
COMMENT ON FUNCTION public.record_resend_registered_email_delivery_event(
  text, text, text, text, text, text, integer, timestamptz, text
) IS 'Service-role-only replay-safe recorder for signed registered NailIQ email delivery receipts.';
COMMENT ON FUNCTION public.load_registered_email_delivery_truth(
  text, text, text, integer
) IS 'Service-role-only PII-free operational read model for registered NailIQ email delivery evidence.';
