-- Folded-history marker for production migration 20260530010432.
-- Original production name: booking_notifications_nullable_sent_at.
-- Its schema effect is represented by the later folded baseline.
