-- Folded-history marker for production migration 20260615023528.
-- Original production name: scope_booking_client_snapshot_to_salon.
-- Its schema effect is represented by the later folded baseline.
