-- Folded-history marker for production migration 20260430160000.
-- Original production name: phase2_salon_setup_and_catalog_write_rls.
-- Its schema effect is represented by the later folded baseline.
